# Buildpack API version
api = "0.6"

# Buildpack ID and metadata
[buildpack]
  id = "alexandreroman/cve-2021-44228-workaround-buildpack"
  version = "1.0.0"

# Stacks that the buildpack will work with
[[stacks]]
  id = "io.buildpacks.stacks.bionic"
